name: "platex Action"
author: "mas-tsukuba"
description: "Compile tex file with platex"
inputs:
  LATEX_FILE_NAME:
    description: "Compile Tex File"
    required: true
    default: "main.tex"
  DIRECTORY:
    description: "Working Directory"
    required: true
    default: "./"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    DIRECTORY: ${{ inputs.DIRECTORY }}
    LATEX_FILE_NAME: ${{ inputs.LATEX_FILE_NAME }}
